main/users/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, PasswordField, EmailField, BooleanField, SelectField, IntegerField
from wtforms.validators import DataRequired, EqualTo, ValidationError
from flask_admin.contrib.sqla import ModelView
from main.models import User


class LoginForm(FlaskForm):
    email = EmailField('მაილი', validators=[DataRequired()])
    password = PasswordField('პაროლი', validators=[DataRequired()])
    submit = SubmitField('შესვლა')


class RegisterForm(FlaskForm):
    firstname = StringField('სახელი',
                           validators=[DataRequired()])
    lastname = StringField('გვარი',
                           validators=[DataRequired()])
    nickname = StringField('მეტსახელი',
                           validators=[DataRequired()])
    email = EmailField('მაილი',
                       validators=[DataRequired()])
    
    password = PasswordField('პაროლი',
                            validators=[DataRequired()])
    confirm_password = PasswordField('გაიმეორეთ პაროლი',
                                    validators=[DataRequired(), EqualTo('password')])
    
    facebook_link = StringField('შენი Facebook პროფილის ლინკი', 
                                validators=[DataRequired()])
    
    submit = SubmitField('რეგისტრაცია')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('This email is taken. Please choose a different one.')
        

class UpdateAccountForm(FlaskForm):
    firstname = StringField('სახელი',
                           validators=[DataRequired()])
    lastname = StringField('გვარი',
                           validators=[DataRequired()])
    nickname = StringField('მეტსახელი',
                           validators=[DataRequired()])
    email = EmailField('მაილი',
                       validators=[DataRequired()])
    
    picture = FileField('Update Profile Picture')

    submit = SubmitField('განახლება')

    def validate_nickname(self, nickname):
        if nickname.data != current_user.nickname:
            user = User.query.filter_by(nickname=nickname.data).first()
            if user:
                raise ValidationError("That nickname is taken. Please choose a different one.")

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError("That email is taken. Please choose a different one.")



class UserForm(FlaskForm):
    firstname = StringField('სახელი',
                            validators=[DataRequired()])
    lastname = StringField('გვარი',
                           validators=[DataRequired()])
    nickname = StringField('მეტსახელი')
    email = EmailField('Email',
                       validators=[DataRequired()])
    rank = SelectField('Rank', choices=[('მოდერატორი', 'მოდერატორი'), ('ხელმძღვანელი', 'ხელმძღვანელი'), ('თანახელმძღვანელი', 'თანახელმძღვანელი'), ('წევრი', 'წევრი')],
                        validators=[DataRequired()])
    in_group = BooleanField("Is this person in a working group?")
    score = IntegerField('Personal Score')
    submit = SubmitField('Save')

class UserView(ModelView):
    form = UserForm
    def on_model_change(self, form, model, is_created):
        return super(UserView, self).on_model_change(form, model, is_created)

main/elements/routes.py
from flask import Blueprint, render_template, request
from main.models import discountElement, eventElement
from datetime import datetime

elements = Blueprint('elements', __name__)


@elements.route('/discounts', methods=['POST', 'GET'])
def discounts_page():
    discount_elements = discountElement.query.all()
    filtered_elements = []
    if request.method == 'POST':
        category = request.form.get('category')
        if category != 'ყველა':
            for discount_element in discount_elements:
                if category in discount_element.categories:
                    filtered_elements.append(discount_element)
            return render_template('discounts_section.html', discount_elements=filtered_elements)
    return render_template('discounts_section.html', discount_elements=discount_elements)

@elements.route("/discount/<string:id>", methods=["POST", "GET"])
def discount_element(id):
    discount_info = discountElement.query.filter_by(id=id).first()
    expiration_duration = discount_info.expiration_duration - datetime.now() 
    print(expiration_duration)
    return render_template('discount_page.html', discount_info=discount_info, expiration_duration=expiration_duration.days)


@elements.route('/events', methods=['POST', 'GET'])
def events_page():
    event_elements = eventElement.query.all()
    filtered_elements = []
    if request.method == 'POST':
        category = request.form.get('category')
        if category != 'ყველა':
            for event_element in event_elements:
                if category in event_element.categories:
                    filtered_elements.append(event_element)
            return render_template('events_section.html', event_elements=filtered_elements)
    return render_template('events_section.html', event_elements=event_elements)

@elements.route("/event/<int:id>", methods=["POST", "GET"])
def event_element(id):
    event_info = eventElement.query.filter_by(id=id).first()
    event_duration = int((event_info.end_date - event_info.start_date).total_seconds() / 3600)
    return render_template('event_page.html', event_info=event_info, event_duration=event_duration)


@elements.route('/student_events', methods=['POST', 'GET'])
def students_event_page():
    student_events = eventElement.query.filter_by(type='1').all()
    print(student_events)
    return render_template('students.html', events=student_events)

@elements.route('/sponsor_events', methods=['POST', 'GET'])
def sponsors_event_page():
    sponsor_events = eventElement.query.filter_by(type='0').all()
    return render_template('sponsors.html', events=sponsor_events)

main/other/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from main.models import discountElement, eventElement, User, email, Group, GroupLogs, FormData
from main.elements.forms import DiscountElementView, EventElementView
from main.groups.forms import GroupView
from main.users.forms import UserView
from main.forms import emailForm, MemberForm, LeaderForm, LogsView
# from main.other.utils import send_activation_email
from flask_mail import Message
from main.auto_correction import process_text
from main.search_system import search_query
from main import db, admin, bcrypt, mail, csrf
import random
import secrets

other = Blueprint('other', __name__)

admin.add_view(DiscountElementView(discountElement, db.session))
admin.add_view(EventElementView(eventElement, db.session))
admin.add_view(UserView(User, db.session))
admin.add_view(GroupView(Group, db.session))
admin.add_view(LogsView(name='Logs', endpoint='logs'))


@other.route("/", methods=['POST', 'GET'])
@other.route("/home", methods=['POST', 'GET'])
def main():
    discount_elements = discountElement.query.all()
    event_elements = eventElement.query.all()
    emails = [email.email for email in email.query.all()]
    email_form = emailForm()

    # shuffling elements
    random.shuffle(discount_elements)
    random.shuffle(event_elements)


    # email verification 
    if email_form.validate_on_submit():
        if email_form.email.data not in emails:
            # send_activation_email(email_form.email.data)
            flash('A confirmation email has been sent to your email address.', 'success')
        else:
            flash('Email has already subscribed', 'warning')

    # search system
    user_query = request.args.get('query')
    if user_query:
        processed_text = process_text(user_query)
        search_results = search_query(processed_text, discount_elements, event_elements)
        print(search_results)
        return render_template('search_results.html', text=processed_text)


    return render_template("index1.html", discount_elements=discount_elements, event_elements=event_elements, email_form=email_form)

@csrf.exempt
@other.route('/fill_path', methods=['POST', 'GET'])
def fill_path():
    if request.method == 'POST':
        if request.form.get('entity') == 'MEMBER':
            return redirect(url_for('other.fill_form_member'))
        
    return render_template('fill_path.html')

@csrf.exempt
@other.route('/fill_form_member', methods=['POST', 'GET'])
def fill_form_member():
    form = MemberForm()
    teams = Group.query.all()
    form.team.choices = [(team.id, f"{team.name}, სამსახური - {team.category}") for team in teams if len(team.members) < 5]
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if not existing_user:
            form_data = FormData(
                firstname=form.firstname.data,
                lastname=form.lastname.data,
                email=form.email.data,
                why_join=form.why_join.data,
                category=form.category.data,
                facebook_link=form.facebook_link.data
            )
            db.session.add(form_data)
            db.session.commit()
            flash('წარმატებით გაიგზავნა ანკეტა, კვალიფიკაციის შემთხვევაში დაგეკონტაქტებით ელფოსტის მეშვეობით.', 'success')
        elif existing_user:
            flash('ელფოსტა დაკავებულია, გთხოვთ სხვა ელფოსტა ჩაწეროთ.', 'danger')
            return redirect(url_for('other.fill_form_member'))

        return redirect(url_for('other.main'))
    return render_template('fill_form.html', form=form, teams=teams)

@other.route('/applied_forms', methods=['POST', 'GET'])
def applied_forms():
    form_data = FormData.query.all()

    return render_template('applied_forms.html', forms=form_data)

@csrf.exempt
@other.route('/user_form/<int:id>', methods=['POST', 'GET'])
def form(id):
    user_form = FormData.query.get(id)
    if request.method == 'POST':
        try:
            if request.form.get('entity') == 'ACCEPT':
                password = secrets.token_hex(16)
                unique_id = secrets.token_hex(8)
                hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
                user = User(unique_id=unique_id, firstname=user_form.firstname, lastname=user_form.lastname,
                            facebook_link=user_form.facebook_link, email=user_form.email, password=hashed_password)
                db.session.add(user)
                db.session.delete(user_form)
                db.session.commit()
                msg = Message('Account Activation', sender='ldzotsenidze4@gmail.com', recipients=[user_form.email])
                msg.body = f'FULL INFO: email: {user_form.email}\npassword: {password}'
                mail.send(msg)

                flash('წარმატებით გაეგზავნა ინფორმაცია მომხმარებელს', 'success')
                return redirect(url_for('other.applied_forms'))

            elif request.form.get('entity') == 'DECLINE':
                db.session.delete(user_form)
                db.session.commit()

                flash('მომხმარებლის განაცხადი უარყოფილია', 'info')
                return redirect(url_for('other.applied_forms'))
        except Exception as e:
            db.session.rollback()
            flash(f"Erorr {str(e)}", 'danger')

    return render_template('user_form.html', form=user_form)

main/users/routes.py
from flask_login import login_user, logout_user, login_required, current_user
from main.users.forms import LoginForm, RegisterForm, UpdateAccountForm
from main import db, bcrypt
from flask import Blueprint, render_template, redirect, url_for, flash, request
from main.users.utils import add_user_info, send_activation_email, save_picture
from main.models import User, NotificationLogs, GroupLogs
import secrets
from flask_socketio import emit


users = Blueprint('users', __name__)



@users.route('/registration', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('other.main'))
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        token = secrets.token_hex(16)
        unique_id = secrets.token_hex(8)
        user = User(unique_id=unique_id, firstname=form.firstname.data, lastname=form.lastname.data, nickname=form.nickname.data,
                    facebook_link=form.facebook_link.data, email=form.email.data, password=hashed_password, activation_token=token)
        db.session.add(user)
        db.session.commit()

        # send activation email
        send_activation_email(form.email.data, token)
    
        add_user_info({
            "email": form.email.data,
            "password": form.password.data
        })

        flash('Registration successful! Please check your email to activate your account.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register_page.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('other.main'))
    form = LoginForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data) and user.is_active:
                login_user(user)
                print(f"Logged in user: {user.email}")
                flash('You have been logged in!', 'success')
                return redirect(url_for('groups.groups_section'))
            elif not user.is_active:
                flash('You have to activate your account first in order to login', 'danger')
            else:
                flash('Login Unsuccessful.', 'danger')
        except:
            flash('Login Unsuccessful.', 'danger')

    return render_template('login_page.html', form=form)

@users.route('/activate/<token>')
def activate(token):
    print(token)
    user = User.query.filter_by(activation_token=token).first()
    if user:
        user.is_active = True
        user.activation_token = None
        db.session.commit()
        flash("Account activated successfully!", 'success')
        return redirect(url_for('users.login'))
    else:
        flash("Invalid or expired token", 'danger')
        return redirect(url_for('users.register'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    notification_log = NotificationLogs.query.filter_by(user_id=current_user.id).order_by(NotificationLogs.id.desc())
    page = request.args.get('page', 1, type=int)
    group_logs = GroupLogs.query.filter_by(group_id=current_user.group_id).order_by(GroupLogs.id.desc()).paginate(page=page, per_page=5)
    
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        current_user.email = form.email.data
        current_user.nickname = form.nickname.data
        db.session.commit()
        flash("Your account has been updated!", 'success')
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.firstname.data = current_user.firstname
        form.lastname.data = current_user.lastname
        form.nickname.data = current_user.nickname
        form.email.data = current_user.email
    image_file = url_for('static', filename='imgs/profile_pics/' + current_user.image_file)

    return render_template('account.html', notification_log=notification_log, group_logs=group_logs,
                           image_file=image_file, form=form)

@users.route("/logout")
@login_required
def logout():
    logout_user()
    flash('Successfully logged out', 'success')
    return redirect(url_for('groups.groups_section'))


@users.route('/all_notifications/<int:id>', methods=['GET', 'POST'])
def user_log(id):
    page = request.args.get('page', 1, type=int)
    notifications = NotificationLogs.query.filter_by(user_id=id).order_by(NotificationLogs.id.desc()).paginate(page=page, per_page=5)
    if request.method == 'POST':
        notifications = NotificationLogs.query.filter_by(user_id=id).all()
        for notification in notifications:
            db.session.delete(notification)
        db.session.commit()
        flash('ყველა შეტყობინება წაიშალა', 'success')

    return render_template('user_log_page.html', notifications_log=notifications)


@users.route('/profile/<string:unique_id>', methods=['GET', 'POST'])
def profile(unique_id):
    user = User.query.filter_by(unique_id=unique_id).first()

    return render_template('profile.html', user=user)

main/templates/applied_forms.html
{% extends 'new_base.html' %}
{% block content %}

<style>
    body {
        background-color: #f9f9f9;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 1200px;
        margin: 20px auto;
        padding: 20px;
    }

    .card {
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
        padding: 20px;
        transition: transform 0.3s, box-shadow 0.3s;
        text-decoration: none;
        color: inherit;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);
    }

    .card p {
        margin: 0;
        padding: 5px 0;
        color: #333;
    }

    .card-header {
        font-size: 1.1rem;
        font-weight: 700;
        color: #007bff;
        margin-bottom: 10px;
    }

    .card-body {
        font-size: 1rem;
    }
</style>

<div class="container">
    {% for applied_form in forms %}
    <a href="{{ url_for('other.form', id=applied_form.id) }}" class="card">
        <div class="card-header">{{ applied_form.id }}</div>
        <div class="card-body">
            <p>{{ applied_form.firstname }} {{ applied_form.lastname }}</p>
        </div>
    </a>
    {% endfor %}
</div>

{% endblock %}

main/templates/discount_page.html
{% extends "base.html" %}
{% block content %}
<img src="static/imgs/DiscountnEventImages/{{discount_info.img}}" alt="{{ discount_info.name }}">
<h2>{{discount_info.name}}</h2>
<p>{{ discount_info.description }}</p>

<p>{{ discount_info.categories }}</p>
<p>Expiration Duration: {{ expiration_duration }} Days</p>
{% endblock content %}

main/templates/group_page.html
{% extends "new_base.html" %}
{% block content %}
    <style>
        @font-face { font-family: BPG; src: url('static/fonts/bpg_nino_mtavruli_bold.ttf'); } 

        body {
            font-family: BPG;
            background-color: #f1f1f1;
            margin: 0;
            padding: 0;
        }

        .btn {
            padding: 10px 20px;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px;
            transition: background-color 0.3s ease;
        }

        .btn-primary {
            background-color: #007bff;
        }

        .btn-primary:hover {
            background-color: #0056b3;
        }

        .btn-danger {
            background-color: #f03c3c;
        }

        .btn-danger:hover {
            background-color: #d32f2f;
        }

        .group-details, .logs-container {
            max-width: 900px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h1, h2 {
            color: #333;
        }

        .group-details p, .logs-list p {
            color: #666;
            margin-bottom: 10px;
        }

        .table-responsive {
            width: 100%;
            overflow-x: auto;
            -webkit-overflow-scrolling: touch;
            margin-top: 20px;
            border-radius: 10px;
        }

        .member-table {
            width: 100%;
            border-collapse: collapse;
            min-width: 600px;
            background: #fff;
            border-radius: 10px;
            overflow: hidden;
        }

        .member-table th, .member-table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        .member-table th {
            background-color: #f2f2f2;
        }

        .member-table tbody tr:hover {
            background-color: #f1f1f1;
        }

        .control-panel-link {
            display: inline-block;
            margin-bottom: 20px;
            padding: 10px 15px;
            background-color: #007bff;
            color: white;
            border-radius: 5px;
            text-decoration: none;
            transition: background-color 0.3s ease;
        }

        .control-panel-link:hover {
            background-color: #0056b3;
        }

        .logs-list {
            margin-top: 10px;
        }

        .logs-list p:hover {
            border-radius: 7px;
            cursor: pointer;
            transition: 0.1s;
            background: rgb(255, 255, 255);
        }

        .pagination {
            margin-top: 20px;
        }

        .page-item.disabled .page-link {
            color: #aaa;
        }

        .page-item.active .page-link {
            background-color: #007bff;
            border-color: #007bff;
            color: white;
        }

        .page-link {
            color: #007bff;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .page-link:hover {
            background-color: #f0f0f0;
        }

        .group-image {
            width: 100%;
            height: 315px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .member-profile-pic {
            width: 30px;
            height: 30px;
            margin-right: 10px;
            border-radius: 50%;
        }

        .description {
            background-color: #f9f9f9;
            padding: 10px;
            border-radius: 5px;
            margin-top: 10px;
        }
    </style>

    <div class="group-details">
        <img src="{{ url_for('static', filename='imgs/team_pics/' + group.image_file) }}" alt="{{ group.name }}" class="group-image">
        
        <h1>{{ group.name }}</h1>
        <br>
        <p>გუნდის ქულა - {{ group.score }}</p>
        <p>გუნდის ხელმძღვანელი - {{ leader.firstname }} {{ leader.lastname }}</p>

        <h2>Members:</h2>
        <div class="table-responsive">
            <table class="member-table table table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>სრული სახელი</th>
                        <th>წოდება</th>
                        <th>პერსონალური ქულა</th>
                    </tr>
                </thead>
                <tbody>
                    {% for member in group.members %}
                        <tr>
                            <td>{{ member.unique_id }}</td>
                            <td>
                                <a href="{{ url_for('users.profile', unique_id=member.unique_id) }}">
                                    <img src="{{ url_for('static', filename='imgs/profile_pics/' + member.image_file) }}" alt="Profile Picture" class="member-profile-pic">
                                    {{ member.firstname }} {{ member.lastname }} <span class="text-muted" style="font-size: smaller;">@{{ member.nickname }}</span>
                                </a>
                            </td>
                            <td>{{ member.rank }}</td>
                            <td>{{ member.score }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="description">
            <h5>გუნდის შესახებ</h5>
            <p>{{ group.description }}</p>
        </div>
        
        {% if not current_user.in_group %}
            <br>
            <form method="POST" action="">
                <p>გინდა ამ გუნდში შესვლა?</p>
                <a href="{{ group.group_form }}" class="btn btn-primary" target="_blank">შეავსე ფორმა</a>
            </form>
        {% endif %}
        
        <br>
        {% if current_user.in_group and current_user.group.id == group.id and current_user.unique_id != leader.unique_id %}
            <a href="{{ url_for('groups.leave_group', id=group.id) }}" class="btn btn-danger">Leave Group</a>
        {% endif %}
        
        {% if current_user.group %}
            {% if current_user.in_group and (current_user.unique_id == leader.unique_id) or (current_user.group.id == group.id and current_user.rank == 'თანახელმძღვანელი') %}
                <a href="{{ url_for('groups.control_panel', id=group.id) }}" class="control-panel-link">Control Panel</a>
            {% endif %}
        {% endif %}
    </div>

    {% if current_user.group_id == group.id %}
        <div class="logs-container">
            <h2>Logs</h2>
            <div class="logs-list">
                {% for group_log in group_logs.items %}
                    <p>{{ group_log.log }}</p>
                    <p style="color: rgba(32, 32, 32, 0.705)">{{ group_log.time }}</p>
                {% endfor %}
            </div>
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% for page_num in group_logs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                        {% if page_num %}
                            {% if group_logs.page == page_num %}
                                <li class="page-item active">
                                    <span class="page-link">{{ page_num }}</span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="{{ url_for('groups.group_page', id=group.id, page=page_num) }}">{{ page_num }}</a>
                                </li>
                            {% endif %}
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">...</span>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        </div>
    {% endif %}
{% endblock content %}

main/templates/index1.html
{% extends "base.html" %}
{% block content %}
<section class="section1">
  <div class="carousel-container">
    <div class="carousels">
      <div class="carousel-img"><a href=""><img src="static/imgs/carouselsImgs/carousel2.jpg" alt="Image 2"></a></div>
      <div class="carousel-img"><a href=""><img src="static/imgs/carouselsImgs/carousel5.jpg" alt="Image 5"></a></div>
      <div class="carousel-img"><a href=""><img src="static/imgs/carouselsImgs/carousel6.jpg" alt="Image 6"></a></div>
      <div class="carousel-img"><a href=""><img src="static/imgs/carouselsImgs/carousel7.jpg" alt="Image 7"></a></div>
      <div class="carousel-img"><a href=""><img src="static/imgs/carouselsImgs/carousel10.jpg" alt="Image 10"></a></div>
    </div>
    <div class="points"></div> 
  </div>
</section>

<div class="text-center my-4">
  <a href="{{ url_for('other.fill_path') }}" class="btn btn-primary btn-lg">ჩაერთე პროექტში</a>
</div>

<h1 class="h1 text-center">ღონისძიებები & ლექციები</h1>
<h6 class="h6 text-center">არ გამოტოვო არცერთი გასაოცარი შეხვედრა</h6>
<section class="section2">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-auto"><button id="prevButton" class="btn btn-outline-secondary"><i class="fa-solid fa-chevron-left"></i></button></div>
      <div class="col">
        <div class="carousel-container">
          <div class="cards">
            {% for element in event_elements %}
              <div class="card mx-2" style="width: 25%;"><a href="{{ url_for('elements.event_element', id=element.id) }}">
                <img src="static/imgs/DiscountnEventImages/{{element.img}}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">{{element.name}}</h5>
                  <p class="card-text">{{element.categories}}</p>
                </div></a>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="col-auto"><button id="nextButton" class="btn btn-outline-secondary"><i class="fa-solid fa-chevron-right"></i></button></div>
    </div>
  </div>   
</section>

<h1 class="h1 text-center">კვირის საუკეთესო ფასდაკლებები</h1>
<h6 class="h6 text-center">არ გამოტოვო კვირის საუკეთესო ფასდაკლებები</h6>
<section class="section3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-auto"><button id="prevButton2" class="btn btn-outline-secondary"><i class="fa-solid fa-chevron-left"></i></button></div>
      <div class="col">
        <div class="carousel-container">
          <div class="cards2">
            {% for element in discount_elements %}
              <div class="card2 mx-2" style="width: 25%;"><a href="{{ url_for('elements.discount_element', id=element.id) }}">
                <img src="static/imgs/DiscountnEventImages/{{element.img}}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">{{element.condition}}</h5>
                  <h6>{{element.name}}</h6>
                  <p class="card-text">{{element.categories}}</p>
                </div></a>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="col-auto"><button id="nextButton2" class="btn btn-outline-secondary"><i class="fa-solid fa-chevron-right"></i></button></div>
    </div>
  </div>
</section>

<script src="./script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

<form method="POST" action="" enctype="multipart/form-data" class="my-4">
  {{ email_form.hidden_tag() }}
  <div class="form-group">
    {{ email_form.email.label(class="form-control-label") }}
    {{ email_form.email(class="form-control form-control-lg") }}
  </div>
  <div class="form-group">
    {{ email_form.submit(class="btn btn-primary btn-lg btn-block") }}
  </div>
</form>

{% endblock content %}

main/templates/search_results.html
{% extends "base.html" %}
{% block content %}
<div>
    <h1>{{ text }}</h1>
</div>
{% endblock content %}